GET http://127.0.0.1:5001/hello
accept: application/json
###

GET http://127.0.0.1:5001/search?startDate=2023-11-01&endDate=2023-11-05&poi=any&doi=any&min_score=5&max_score=6
accept: application/json
###
